name: Build, test, package

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  pull_request:
    branches:
      - main

jobs:
  cxx-build-workflow:
    uses: InsightSoftwareConsortium/ITKRemoteModuleBuildTestPackageAction/.github/workflows/build-test-cxx.yml@v5.4.6
    with:
      itk-git-tag: '5eb11e272c'
      itk-cmake-options: '-DModule_ITKIODCMTK:BOOL=ON'
